FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# NanoGrid

Nanogrid API v 0.1

Conventions
-----

+ Date formatting uses RFC3339 nano format (2006-01-02T15:04:05.999999999Z07:00)
+ Attribute _ticks_ denotes time in ticks [1 tick = 100 nanos] (https://msdn.microsoft.com/en-us/library/system.datetime.ticks\(v=vs.110\).aspx)




## Data Structures

### Ticks (number) - Time in ticks

### Timestamp (enum)
+ ticks: 0 (number)
+ date:  `2016-02-21T18:06:43.0000000Z` (string) 

### Error 
+ error: `error desc` (string,required)

### NotFound 
+ found: false (boolean,required)


### Version (object)
+ major: 1 (number, required)
+ minor: 1 (number, required)
+ patch: 1 (number, required)
+ extension: RC1 (string, optional)

### TaskConfiguration (object)
+ image: ntx4:2.0.1 (string, required) - docker image
+ cmd: /bin/bash (string,optional) - command to run (cannot be set with args)
+ args (array[string])
    - run
    - L
    - trace
+ cpus: 0.5 (number, required)
+ mem: 1024 (number, required)
+ port: 7777 (number, required)
+ env (object) - docker environment variables
    - TASK_ID: 25
+ labels (object) - docker labels
    - VERSION:  2.0.1
  

### FullTaskConfiguration (TaskConfiguration)
+ name: ntx4 (string, required)
+ version (Version, required)
+ created:  `2016-03-08T06:17:48.227896671Z` (string) -  RFC3339 nano format


## Group Task Repository

Task repository provides api for task configurations. 

**Task configuration**

Represents blueprint that can be scheduled by NanoGrid schedulers. 
Each configuration has unique _name:version_ identifier that represents immutable blueprint.
Methods for deleting and upsert (when doing reinsert with different configuration) should be used with caution. 

Versions must follow [Semantic Versioning 2.0.0](http://semver.org/)

### Tasks [/tasks]

### List [GET]

List task names

+ Response 200 (application/json)
    + Attributes
         + names (array[string])
            - ntx4
            - reverse-proxy

### Task versions [/tasks/{name}]
+ Parameters
    + name: ntx4 (string)

### List [GET]

List task versions

+ Response 200 (application/json)
    + Attributes (array[Version])


### Task configuration [/tasks/{name}/{version}]

+ Parameters
    + name: ntx4 (string)
    + version: 2.0.0(string)


### Get [GET]

+ Response 200 (application/json)
    + Attributes (FullTaskConfiguration)


### Upsert [POST]

Should be used only as immutable insert with possible retry in production (eventual consistency by default).
Allows update to support retry operation and testing puproses.

+ Request (application/json)
    + Attributes (TaskConfiguration)

+ Response 204

### Delete [DELETE]

+ Response 204

## Data Structures

### TaskDescriptor
+ name: nginx (string,required)
+ version: 1.8.1 (string, required)

### SchedulerTaskTimeInfo
+ created: `2016-04-12T18:22:23.454561444Z` (string, required)
+ scheduled: `2016-04-12T18:23:23.454561444Z` (string, required)
+ started: `2016-04-12T18:23:23.854561444Z` (string, required)

### SchedulerTask
+ id: `e14820ed-3ded-40b2-9587-0602bb5221d1` (string, required)
+ allocatorId: `a4dc7a8f-2cc5-49d9-afef-79c7160d24d2` (string, required)
+ endpoint: `http://192.168.55.242:31000` (string, required)
+ lastPing: `2016-04-12T18:22:23.45456313Z` (string, required)
+ config (TaskConfiguration, required)
+ timeInfo (SchedulerTaskTimeInfo, required)


## Group Task Scheduler

### Allocators [/allocators]

### List Allocators IDs [GET]

+ Response 200 (application/json)
    + Attributes (array[string])
       - `a4dc7a8f-2cc5-49d9-afef-79c7160d24d2`

### Allocator [/allocators/{allocatorId}]

### Kill Allocator [DELETE]
+ Response 204

+ Response 404 (application/json)
    + Attributes
      + found: false (boolean, required)

### Allocator Tasks [/allocators/{allocatorId}/tasks]
+ Parameters
    + allocatorId: `a4dc7a8f-2cc5-49d9-afef-79c7160d24d2` (string)

### List Tasks [GET]

+ Response 200 (application/json)
    + Attributes (array[SchedulerTask])


### Schedule Task [POST]
+ Request (application/json)
    + Attributes (TaskDescriptor)

+ Response 201 (application/json)
    + Attributes
      + id: `a4dc7a8f-2cc5-49d9-afef-79c7160d24d2` (string,required)


### Allocator Task [/allocators/{allocatorId}/tasks/{taskId}]
+ Parameters
    + allocatorId: `a4dc7a8f-2cc5-49d9-afef-79c7160d24d2` (string)
    + taskId: `d4dc7a8f-2cc5-49d9-afef-79c7160d24d2` (string)
    

### Get Task [GET]

+ Response 200 (application/json)
    + Attributes (SchedulerTask)

+ Response 202 (application/json)
    Task is not ready yet

    + Attributes (SchedulerTask)

+ Response 404 (application/json)
    + Attributes
      + found: false (boolean, required)
  


### Kill Task [DELETE]

+ Response 204

+ Response 404 (application/json)
    + Attributes
        + found: false (boolean, required)


### Allocator Ping [/allocators/{allocatorId}/tasks/ping]

Every allocator musr periodically ping with list of active task ids to avoid task GC after inactive interval


### Ping [POST]

+ Request (application/json)
    + Attributes (array[string])
        + `d4dc7a8f-2cc5-49d9-afef-79c7160d24d2`

+ Response 204


## Data Structures

### XMLDuration (string) - ISO 8601 XMLDuration 

### Stream
+ id: `d4dc7a8f-2cc5-49d9-afef-79c7160d24d2` (string,optional) - force id if specified
+ name: mystream (string,required)
+ offset (Timestamp, required)
+ tags (array[string],optional)
    - test

### AdaptationMimeType (enum)
+ audio/mp4
+ video/mp4

### BaseRepresentation
+ id: 500kbps (string, required)
+ codecs: mp4a.40.2 (string, required)
+ bandwidth: 512000 (number, required)
+ header: 9e107d9d372bb6826bd81d3542a419d6 - header MD5 (string, required)

### AudioRepresentation (BaseRepresentation)
+ audioSamplingRate: 44100 (number, required)

### VideoRepresentation (BaseRepresentation)
+ width: 720 (number, required)
+ height:  576 (number, required)
+ par: `16:9` (string, required)
+ sar: `64:45` (string, required)
+ frameRate: 25/1 (string, required)

### AdaptationSet
+ id: 720p (string, required)    
+ mimeType (AdaptationMimeType, required)
+ segmentAlignment: true (boolean, required)
+ startWithSAP: 1 (number, required)
+ lang: cze (string, optional)
+ representations (array,required)
    - (AudioRepresentation)
    - (VideoRepresentation)

### Period
+ offset (Ticks, required) - offset in ticks to stream start time
+ closed: false (boolean, optional)
+ adaptationSets (array[AdaptationSet],required)

### IdedPeriod (Period)
+ id: `d4dc7a8f-2cc5-49d9-afef-79c7160d24d2`  (string,required)

### Chunk
+ offset: 10000000 (number,required)
+ duration: 10000000 (number, required)


## Group Stream Server

### Streams [/streams{?page,size}]

### List [GET]
+ Parameters
    + page: 0 (number)
    + size: 10 (number)
    
+ Response 200 (application/json)
    + Attributes (array[Stream])
 `  
+ Response 404 (application/json)
    + Attributes (NotFound)

### Create [POST]
+ Request (application/json)
    + Attributes (Stream)

+ Response 201 (application/json)
    + Attributes
        + id: `f47ac10b-58cc-4372-a567-0e02b2c3d479` (string)

+ Response 400 (application/json)
    + Attributes (Error)

+ Response 409 (application/json)
    + Attributes (Error)
    

### Headers [/headers]

### Add [POST]
+ Request (application/octet-stream)
    + Body
    
            <raw header data>


+ Response 201 (application/json)
    + Attributes
        + id: `9e107d9d372bb6826bd81d3542a419d6` (string)


### Header [/headers/{id}]
+ Parameters
    + id: `9e107d9d372bb6826bd81d3542a419d6` (string)

    
### Get [GET]
+ Response 200 (application/octet-stream)    
    + Body
    
            <raw header data>

+ Response 404 (application/json)
    + Attributes (NotFound)

### Stream [/streams/{streamId}]
+ Parameters
    + streamId: `a4dc7a8f-2cc5-49d9-afef-79c7160d24d2` (string)
    

### Get [GET]
+ Response 200 (application/json)
    + Attributes (Stream)

+ Response 404 (application/json)
    + Attributes (NotFound)

### Delete [DELETE]
+ Response 204

+ Response 404 (application/json)
    + Attributes (NotFound)

### Stream Periods [/streams/{streamId}/periods{?page,size,offset,reverse}]
+ Parameters
    + streamId: `a4dc7a8f-2cc5-49d9-afef-79c7160d24d2` (string)

    
### List [GET]
+ Parameters
    + page: 0 (number)
    + size: 100 (number)
    + offset: 0 (Ticks)
    + reverse: true (boolean)

+ Response 200 (application/json)
    + Attributes (array[IdedPeriod])

 
### Append [POST]
    
Period can be appended only after all previous periods are closed and its offset must be greated than latest period offset (offset attribute)

+ Request (application/json)
    + Attributes (Period)

+ Response 201 (application/json)
    + Attributes
        + id: `f47ac10b-58cc-4372-a567-0e02b2c3d479` (string,required)

+ Response 400 (application/json)
    + Attributes (Error)

+ Response 404 (application/json)
    + Attributes (NotFound)

+ Response 409 (application/json)
    + Attributes (Error)

### Stream Period [/streams/{streamId}/periods/{periodId}]
+ Parameters
    + streamId: `a4dc7a8f-2cc5-49d9-afef-79c7160d24d2` (string)
    + periodId: `f47ac10b-58cc-4372-a567-0e02b2c3d479` (string)

### Get [GET]
+ Response 200 (application/json)
    + Attributes (IdedPeriod)

+ Response 404 (application/json)
    + Attributes (NotFound)

### Delete [DELETE]
+ Response 204

+ Response 404 (application/json)
    + Attributes (NotFound)


### Close Period [/streams/{streamId}/periods/{periodId}/close]
+ Parameters
    + streamId: `a4dc7a8f-2cc5-49d9-afef-79c7160d24d2` (string)
    + periodId: `f47ac10b-58cc-4372-a567-0e02b2c3d479` (string)

### Close [POST]

+ Response 204

+ Response 404 (application/json)
    + Attributes (NotFound)

+ Response 409 (application/json)
    + Attributes (Error)


### Period Manifest [/streams/{streamId}/periods/{periodId}/{type}.mpd{?from,to,liveOffset}]
+ Parameters
    + streamId: `a4dc7a8f-2cc5-49d9-afef-79c7160d24d2` (string)
    + periodId: `f47ac10b-58cc-4372-a567-0e02b2c3d479` (string)
    + type (enum)
        - live (string)
        - ondemand (string)
    + from (Timestamp, optional) - ondemand only
    + to (Timestamp, optional) - ondemand only
    + liveOffset (Timestamp, optional) - live only - shift meaning of live stream now to past (for live streaming of ondemand streams) 


### Get [GET]
+ Response 200 (application/xml)
    + Body

+ Response 400 (application/json)
    + Attributes (Error)

+ Response 409 (application/json)
    + Attributes (Error)    

+ Response 404


### Period Adaptation Header [/streams/{streamId}/periods/{periodId}/adaptation/{adId}/header]
+ Parameters
    + streamId: `a4dc7a8f-2cc5-49d9-afef-79c7160d24d2` (string)
    + periodId: `f47ac10b-58cc-4372-a567-0e02b2c3d479` (string)
    + adId: 720p (string)


### List [GET]

+ Response 200 (application/octet-stream)    
    + Body
    
            <raw header data>

### Stream Chunks [/streams/{streamId}/periods/{periodId}/adaptation/{adId}/representation/{reprId}/chunks{?page,size,offset,reverse}]
+ Parameters
    + streamId: `a4dc7a8f-2cc5-49d9-afef-79c7160d24d2` (string)
    + periodId: `f47ac10b-58cc-4372-a567-0e02b2c3d479` (string)
    + adId: 720p (string)
    + reprId: 512kbps (string)
    + page: 0 (number)
    + size: 10 (number)
    + offset: 0 (Ticks)
    + reverse: true (boolean)

### List [GET]
+ Response 200 (application/json)
    + Attributes (array[Chunk])

+ Response 204
    
    Returned when there is no more content in selected direction (stream closed when reverse=false, before first chunk when reverse=true).
    
    + Body
   


### Stream Chunks [/streams/{streamId}/periods/{periodId}/adaptation/{adId}/representation/{reprId}/chunks]
+ Parameters
    + streamId: `a4dc7a8f-2cc5-49d9-afef-79c7160d24d2` (string)
    + periodId: `f47ac10b-58cc-4372-a567-0e02b2c3d479` (string)
    + adId: 720p (string)
    + reprId: 512kbps (string)


### Write [POST]
+ Request (application/octet-stream)

    + Headers
    
            Offset: 10000
            Duration: 10000000
            
    + Body
    
            <raw chunk data>

+ Response 204


### Stream Chunk [/streams/{streamId}/periods/{periodId}/adaptation/{adId}/representation/{reprId}/chunks/{offset}]
+ Parameters
    + streamId: `a4dc7a8f-2cc5-49d9-afef-79c7160d24d2` (string)
    + periodId: `f47ac10b-58cc-4372-a567-0e02b2c3d479` (string)
    + adId: 720p (string)
    + reprId: 512kbps (string)
    + offset: 100000 (Ticks)

### Read [GET]
+ Response 200 (application/octet-stream)

    + Headers
    
            Duration: 10000000
            
    + Body
    
            <raw chunk data>




## Data Structures

### Execution
+ partitions: 1 (number, optional) - number of tasks
+ executors: 1 (number, required) - max concurrency (max number of tasks that can run in parallel)

### Manifest (object)
+ template: http://myhost/259/$START$/$DURATION$/offline.ism/manifest.mpd (string, required)
+ start (Timestamp, required)
+ end (Timestamp, required)

### LiveStream (object)
+ manifest (Manifest,required)
+ maxDelay (Timestamp, optional) - allows arbitrary delay when not set

### OfflineStream (object)
+ manifest (Manifest,required)

### PlanState (object)
+ state (enum)
    - STATE_WAITING
    - STATE_RUNNING
    - STATE_COMPLETED
    - STATE_FAILED
+ reason: no free resources (string, optional)
+ started:  `2016-02-21T18:06:43.0000000Z` (string, required)
+ completed (string, optional)


### StreamSource
+ live (LiveStream, optional)
+ offline (OfflineStream, optional)
+ execution (Execution, required)

### Plan
+ id: `f47ac10b-58cc-4372-a567-0e02b2c3d479` (string) - UUIDv4 key
+ state (PlanState, required)
+ source (StreamSource, required)

### EventTimestamp
+ type (enum, required)
    - ts
    - rts
    - flush

+ val (Ticks, required)

### EventLabel
+ type (enum, required)
    - item
    - plus
+ val (Ticks, required)

### EventData
+ type (enum, required)
    - audio
+ val (string, required) - Base64 encoded binary data

### Event
+ type: label (string, required)
+ lookahead: false (boolean, required)
+ timestamp (EventTimestamp, optional)
+ date (EventData, optional)
+ label (EventLabel, optional)

### EventWithOffset
+ offset: 255 (Ticks,required)
+ event (Event, required)

### RecoverableEventWithOffset
+ streamId: ct24 (string,required)
+ publisherId: publisher1 (string,required)
+ event (EventWithOffset,required)
+ recoveryOffset: 258 (Ticks,required)


## Group Speech Recognition

NanoGrid applications.

Streams
-----

+ Stream is represented by stream id _SID_. 
    + SIDs can be reused
    + Multiple non-overlapping tasks can be run for single SID
    + Results are fetched based on SID


Timestamps structures contains ticks or date (date attribute takes precendence).


### Streams [/speech/streams/{streamId}]
+ Parameters
    + streamId: ct24 (string)


### List plans [GET]

+ Response 200 (application/json)
    + Attributes (array[Plan])

    
### Delete [DELETE]    

Remove all data associated with stream

+ Response 202  


### Add source [PUT]

Creates new plan from given source

+ Request (application/json)
    + Attributes (StreamSource)

+ Response 201
    + Attributes
        + id: `f47ac10b-58cc-4372-a567-0e02b2c3d479` (string,required) - planId
        
+ Response 409

### Stream Plan [/speech/streams/{streamId}/plan/{planId}]
+ Parameters
    + streamId: ct24 (string)
    + planId: `f47ac10b-58cc-4372-a567-0e02b2c3d479` (string,required)

### Get plan [GET]

+ Response 200 (application/json)
    + Attributes (Plan)

### Kill plan [DELETE]

Does not remove existing output data

+ Response 202

+ Response 404


## Group Speech Recognition Output

### Streaming output [/speech/streams/{streamId}/output{?fromDate,toDate,fromTicks,toTicks,planId}]

+ Parameters
    + streamId: ct24 (string)
    + fromDate (optional)
    + toDate (optional)
    + fromTicks (optional)
    + toTicks (optional)
    + planId (optional)

### Read [GET]

Responds with chunked plain text reponse, on each line is one json serialized event (example of one such event is in response example)

+ Response 200 (application/json)
    + Attributes (RecoverableEventWithOffset)